# Generated by Django 5.2.5 on 2025-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_name_alter_hotelfloor_floor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='iaq_sensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='life_being_sensor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
