volumes:
  smart_building_local_postgres_data: {}
  smart_building_local_postgres_data_backups: {}

services:

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smart_building_production_postgres
    container_name: smart_building_local_postgres
    volumes:
      - smart_building_local_postgres_data:/var/lib/postgresql/data
      - smart_building_local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres
