# Generated by Django 5.2.5 on 2025-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('datetime', models.DateTimeField()),
                ('device_id', models.TextField()),
                ('datapoint', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
    ]
