# Generated by Django 5.2.5 on 2025-08-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='device_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='rawdata',
            index=models.Index(fields=['device_id'], name='raw_data_ra_device__97d13b_idx'),
        ),
    ]
